### ISSUE TITLE
Handle Panda's ValueError, just in case of MASH error

### ISSUE THREAD

**Issue by andrewsanchez** [andrewsanchez/NCBITK#21]
Got this error from Pandas:

`ValueError: Length mismatch: Expected axis has 135 elements, new values have 0 elements`

as a result of an inexplicable MASH error:

```
ERROR: Did not find fasta records in "genbank/bacteria_renamed/Chlamydia_trachomatis/GCA_000220105.1_Chlamydia_trachomatis_L2c_Complete_Genome.fasta".
```

These errors occurred when trying to run quality_filters.py on genbank/bacteria_renamed, but did not occur when running on just genbank/bacteria_renamed/Chlamydia_trachomatis

**Comment by andrewsanchez** [comment]
@jasonsahl Have you ever seen this error from MASH?

`ERROR: Did not find fasta records in "genomes/Escherichia_coli/GCA_001615895.1_Escherichia_coli_swine45_Contig.fasta".`

When I tried running the filters in a slurm array, I got the error for the above genome.  When I tried to run it directly on the *E. coli directory*, I got the error for a different genome.  I didn't get this error on 653 and don't see anything wrong with those FASTA's.  Any idea's?  I'm not sure how to go about handling this error.

**Comment by jasonsahl** [comment]
No, never seen it, but seems like it’s a path issue. Can you send the full command?

**Comment by andrewsanchez** [comment]
It's weird because it runs fine, creating the sketch file, until it gets to the last genome in the directory.  Stranger still, wI just tried it again (without making any changes to the directory whatsoever) and didn't get the error.

The mash command is being called from the python script, `NCBITK/quality_filters.py` in the function:

```python
def mash(FASTA_dir, mash_exe):
    sketch_file = os.path.join(FASTA_dir, "all.msh")
    all_fastas = os.path.join(FASTA_dir, "*.fasta")
    distance_matrix = os.path.join(FASTA_dir, "distance_matrix.csv")
    sketch_command = "{} sketch -o {} {}".format(mash_exe, sketch_file, all_fastas)
    distance_command = "{} dist -p 4 -t {} {} > {}".format(mash_exe, sketch_file, all_fastas, distance_matrix)
    Popen(sketch_command, shell="True").wait()
    Popen(distance_command, shell="True").wait()
```

and the script is being run in `/scratch/aas229/jobs/genbank_qc_array.sh`:

```bash
#!/bin/bash

#SBATCH --job-name=genbank_qc
#SBATCH --time=5:00:00
#SBATCH --workdir=/scratch/aas229
#SBATCH --output=jobs/output_genbank_qc_array.txt

# get line count of file containing dirs to be used as argument to $cmd below
array_size=`wc -l jobs/qc_target_dirs.txt | cut -f1 -d' '`
#SBATCH --array=1-$array_size
module load anaconda/3.latest
dir=$(sed -n "$SLURM_ARRAY_TASK_ID"p jobs/qc_target_dirs.txt)
cmd="python /common/contrib/tools/NCBITK/quality_filters.py -d"
srun $cmd $dir

```
