### ISSUE TITLE
Filtering based on contigs

### ISSUE THREAD

**Issue by andrewsanchez** [andrewsanchez/NCBITK#31]
@jasonsahl 

You said you would never want to filter out a FASTA that has only 1 contig.

In this case, we can immediately exclude FASTA's that have just 1 contig (since we know we want to keep them) when looking at the statistics for the contigs.   Getting rid of these low values that would be helpful to avoid screwing up the mean and STD..  

Do you also want to always keep FASTA's with fewer than `x` contigs?  Should we set a default value for `x` that can be user defined?  What should that value be?

**Comment by jasonsahl** [comment]
We would want to keep anything with fewer than 10 contigs, I would guess.
